### ISSUE TITLE
Submission page is not showing in the UI.

### ISSUE THREAD

**Issue by thiyagu06** [appirio-tech/tc-common-tutorials#15]
Refer the screen shot.
![screenshot from 2017-04-13 20 31 13](https://cloud.githubusercontent.com/assets/2901614/25010636/5dd1bd90-2088-11e7-9813-7e7095097d34.png)

**Comment by skyhit** [comment]
@thiyagu06 probably, the challenge is passed

**Comment by thiyagu06** [comment]
Is there way to create a challenge? If so can you provide me the json for creating the challenge?
