### ISSUE TITLE
Error downloading Java 7 while building Docker image 

### ISSUE THREAD

**Issue by hazim1093** [appirio-tech/tc-common-tutorials#19]
While building the docker image for [tc-website:base](https://github.com/appirio-tech/tc-common-tutorials/blob/master/docker/tc-website/base/Dockerfile), the command for downloading Java 7 fails. 

The link [http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jdk-7u79-linux-x64.rpm](http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jdk-7u79-linux-x64.rpm) results in `404 Not Found`

Where as if the link is updated to [http://download.oracle.com/otn/java/jdk/7u79-b15/jdk-7u79-linux-x64.rpm](http://download.oracle.com/otn/java/jdk/7u79-b15/jdk-7u79-linux-x64.rpm), it results in `401 Authorization Required` as Oracle has made the download links for Java 7 private.

**Comment by forgot93** [comment]
I have encountered the same problem.

**Comment by sah2ed** [comment]
The `base` docker image is unchanged so an easy workaround for local deployment is to execute:
```
docker pull appiriodevops/tc-website:base
```
which will download a prebuilt copy of the image (prior to the 401 issue). This allows you to rebuild locally the `build` and `run` layers which depend on the `base` image.
