### ISSUE TITLE
Jsp changes not getting picked

### ISSUE THREAD

**Issue by abhinav-koppula** [appirio-tech/tc-common-tutorials#8]
I have the following folder structure:
direct-app - git repo of topcoder direct-app
direct-app-deploy - directory with unzipped jboss-4.2.3.GA

I followed the instructions given in tc-common-tutorials to build direct app and am able to get the site running on my local.
These are the values of the env variables.
```${DIRECT_APP_SRC_ROOT} = /home/abhinav/Documents/Projects/direct-app```
```${BUILT_DATA} = /home/abhinav/Documents/Projects/direct-app-deploy```
```${BUILT_JBOSS_DIR} = /home/abhinav/Documents/Projects/direct-app-deploy/jboss-4.2.3.GA```

However, when I am making changes in the jsp files in direct-app project (cloned repo), and then run 
```docker-compose up tc-direct-build``` followed by
```docker-compose up tc-direct```
my changes do not get picked up. 

What am I doing wrong?
I'm a bit new to this, so please bear with me.

**Comment by skyhit** [comment]
@abhinav-koppula you should run with `docker-compose up tc-direct-with-volume`
